//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.19 at 01:41:41 AM IST 
//


package com.coderunner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="coderun" type="{http://www.coderunner.com}codeRun"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "runCodeResponse")
public class RunCodeResponse {

    @XmlElement(required = true)
    protected CodeRun coderun;

    /**
     * Gets the value of the coderun property.
     * 
     * @return
     *     possible object is
     *     {@link CodeRun }
     *     
     */
    public CodeRun getCoderun() {
        return coderun;
    }

    /**
     * Sets the value of the coderun property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeRun }
     *     
     */
    public void setCoderun(CodeRun value) {
        this.coderun = value;
    }

}
